services:
  app:
    build:
      context: .
      target: ${ENVIRONMENT}
    platform: linux/amd64
    environment:
      - DJANGO_SECRET_KEY=${DJANGO_SECRET_KEY}
      - DJANGO_DEBUG=${DJANGO_DEBUG}
      - DJANGO_SECURE_SSL_REDIRECT=${DJANGO_SECURE_SSL_REDIRECT}
      - DJANGO_SECURE_HSTS_SECONDS=${DJANGO_SECURE_HSTS_SECONDS}
      - DJANGO_SECURE_HSTS_INCLUDE_SUBDOMAINS=${DJANGO_SECURE_HSTS_INCLUDE_SUBDOMAINS}
      - DJANGO_SECURE_HSTS_PRELOAD=${DJANGO_SECURE_HSTS_PRELOAD}
      - DJANGO_SESSION_COOKIE_SECURE=${DJANGO_SESSION_COOKIE_SECURE}
      - DJANGO_CSRF_COOKIE_SECURE=${DJANGO_CSRF_COOKIE_SECURE}
      - CACHE_REDIS_URL=${CACHE_REDIS_URL}
      - ENVIRONMENT=${ENVIRONMENT}
    env_file:
      - .env
    ports:
      - "8000:8000"
    develop:
      watch:
        - action: sync
          path: ./src/
          target: /app/src
        - action: rebuild
          path: pyproject.toml